### PR TITLE
Set ConnectionMonitor-thread to daemon to avoid blocking shutdown.

### PR DESCRIPTION
**Pull request by kagkarlsson**
We cannot rely on a shutdown-signal and there is no support for explicit `stop()`. Making into daemon-thread

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Manually verified this solves the problem with app-shutdown

**Review by evenh — APPROVED** [review]

**Comment by kagkarlsson** [comment]
Slightly cold feet on removing the shutdown hook. It might still be useful to avoid this thread running after the http-client has been shutdown in normal shutdown scenarios. Verified with Even.

**Comment by runeflobakk** [comment]
So it is the shutdown hook itself that may never run? Even though it has been added to the runtime? The invocation to `ConnectionMonitor.shutdown()` never takes place? Or is it invoked, but not effective? Is the JVM shut down in a way circumventing the shutdown hooks?

**Comment by kagkarlsson** [comment]
It appears `HttpClientBuilder` now has built-in support for idle connection evictor, using that instead!

**Comment by kagkarlsson** [comment]
> So it is the shutdown hook itself that may never run? Even though it has been added to the runtime? The invocation to ConnectionMonitor.shutdown() never takes place? Or is it invoked, but not effective? Is the JVM shut down in a way circumventing the shutdown hooks?

Shutdown hooks will not run unless a normal shutdown signal is received or we explicitly call `System.exit()`. May happen when the `main` method for starting applications throws an exception before successful start of the app

**Comment by kagkarlsson** [comment]
Maybe we should upgrade to `v5.1.3` aswell 🤔

**Comment by runeflobakk** [comment]
Makes sense. If there are any non-daemon threads running when the main thread ends (normally or by throwing an exception), and there has been no signal received by the JVM to shut down, the JVM should continue running. Anyway, a monitor thread should probably be a daemon thread.

But I am guessing that if the JVM is in a state where there is no non-daemon "user threads" left, i.e. the main thread has ended normally or by exception, and any forked non-daemon threads have also ended, the JVM _is_ shutting down even though it may not have received a signal to shut down, and shutdown hooks would be run.

Again, it probably makes sense to have the monitoring thread as a daemon thread. But it _may_ also be relevant to leave an option for an explicit shutdown of the monitoring thread, as I guess it is tied to one instance of an HTTP client? It may not be relevant for our use to instantiate and shutdown HTTP clients which are not tied to the startup and shutdown of the application, but it may be a use case, so it _may_ be relevant to also tie a controlled shutdown of the monitor thread to shutdown (i.e. `.close()`) of a HTTP client.

**Comment by runeflobakk** [comment]
haha, great minds!
Screenshot 2022-03-25 at 10 28 36

**Comment by kagkarlsson** [comment]
> But I am guessing that if the JVM is in a state where there is no non-daemon "user threads" left, i.e. the main thread has ended normally or by exception, and any forked non-daemon threads have also ended, the JVM is shutting down even though it may not have received a signal to shut down, and shutdown hooks would be run.

Yes! :) 

> Again, it probably makes sense to have the monitoring thread as a daemon thread. But it may also be relevant to leave an option for an explicit shutdown of the monitoring thread, as I guess it is tied to one instance of an HTTP client? It may not be relevant for our use to instantiate and shutdown HTTP clients which are not tied to the startup and shutdown of the application, but it may be a use case, so it may be relevant to also tie a controlled shutdown of the monitor thread to shutdown (i.e. .close()) of a HTTP client.

Yeah, agreed

**Comment by kagkarlsson** [comment]
Verified the new build solves the problem we experienced.

**Review by evenh — APPROVED** [review]

**Comment by kagkarlsson** [comment]
Releaser i tag `4.1.0`

**Pull request merged**
